name: SWGOH Gamedata

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests brotli
      - run: python generate.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
